### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by lukastomasek** [ahmedmohamed641/movie-app#1]
- Use this [design](https://www.figma.com/community/file/1054327700155381422/movie-listing-web-app)
- Copy  the screens: `Home` and `Details Page`
---

## App functionality:
1. Home page:
  - Should show first 10 popular movies by default
  - Should have options to filter by **comedies**, **action**, **horror**, and **romance**
  - User should be able to search for specific movie. If movie is not found show some message that says `Sorry, we couldn't found the movie`
  - When user clicks on any movie, the app should redirect user to  `Details page`
  - Details Page should show this info:
     - title
     - description
     - type
     - release date
     - runtime
     - genres 
     - rating
     - image of the movie

Technolgies for this project:
 - Vite JS
 - Tailwind 
 - JSDoc 

API:
- [movie db](https://developer.themoviedb.org/docs/getting-started) 
- Create developer account and generate API key (use .ENV) file to hide your secret keys (look up tutorial)

---
## Requirements:

- [ ] Use semantic html
- [ ] Use tailwind best practices
- [ ]  Use js best practices and **ES6** (arrow functions, import & export, etc..)

---
## Deadline
- the project is due in 2 weeks **MAY 20, 2024**
